[tools]
go = "1.26"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"

[env]
_.file = ".envrc"
TLS_CERT_PATH="cert/cert.pem"
TLS_KEY_PATH="cert/key.pem"
HTTP_LISTEN_HOST = ":80"
HTTPS_LISTEN_HOST = ":443"
HTTP3_LISTEN_HOST = ":17443"

[tasks]
start = "go run ."
