apiVersion: apps/v1
kind: Deployment
metadata:
  name: whomst
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whomst
    spec:
      volumes:
        - name: certs
          secret:
            secretName: netzle-net-tls
      setHostnameAsFQDN: true
      containers:
        - name: application
          image: whomst
          envFrom:
            - configMapRef:
                name: whomst-config

          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: "/etc/tls"
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 80
              path: /healthz
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 80
              path: /healthz
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 443
              name: http3
              protocol: UDP
