apiVersion: v1
kind: Service
metadata:
  name: whomst
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "netzle.net,www.netzle.net,debug.netzle.net"
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci-network-load-balancer.oraclecloud.com/is-preserve-source: "true"
    oci.oraclecloud.com/security-rule-management-mode: "NSG"
spec:
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  externalTrafficPolicy: Local
  selector:
    app: whomst
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: kubernetes.io/h2c
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: http3
      port: 443
      protocol: UDP
      targetPort: http3
